(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"EFT_subGeV_DM_rho",
  Authors -> {"Adam Coogan", "Logan Morrison"},
  Date -> "2/13/2018",
  Institutions -> {"UC Santa Cruz"},
  Emails -> {"acoogan@ucsc.edu", "loanmorr@ucsc.edu"},
  Version -> 1};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["\\pi", Null, "0"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mpi0,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["\\pi", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mpi,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> ComposedChar["K", Null, "0"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk0,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["K", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk,
    Indices -> {} },

S[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\eta",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> meta,
    Indices -> {} },

S[7] == {
    SelfConjugate -> True,
    PropagatorLabel -> s,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> ms,
    Indices -> {} },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> A,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\rho",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mrho,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "\\nu",
    PropagatorArrow -> Forward,
    PropagatorType -> Straight,
    Mass -> 0,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorArrow -> Forward,
    PropagatorType -> Straight,
    Mass -> ml,
    Indices -> {} },

F[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> "\\chi",
    PropagatorArrow -> Forward,
    PropagatorType -> Straight,
    Mass -> mx,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];

mpi0[ ___ ] := mpi0;
mpi[ ___ ] := mpi;
mk0[ ___ ] := mk0;
mk[ ___ ] := mk;
meta[ ___ ] := meta;
ms[ ___ ] := ms;
mrho[ ___ ] := mrho;
ml[ ___ ] := ml;
mx[ ___ ] := mx;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[5] , S[5] , S[5] , S[5] ] == {{I*gc1, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[3] , -S[3] ] == {{(2*I)*b0*gc2*(mdq + 3*msq), 0}, {(6*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(6*I)*gc2, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-2*I)*b0*gc3*(mdq + msq), 0}, {(2*I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(2*I)*gc3, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] ] == {{I*b0*gc4*(mdq + 2*msq + muq), 0}, {I*gc4, 0}, {I*gc4, 0}, {(-2*I)*gc4, 0}, {(-2*I)*gc4, 0}, {I*gc4, 0}, {I*gc4, 0}},

C[ S[5] , S[5] , S[4] , -S[4] ] == {{(2*I)*b0*gc5*(3*msq + muq), 0}, {(6*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(6*I)*gc5, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*b0*gc6*(msq + muq), 0}, {(2*I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(2*I)*gc6, 0}},

C[ S[5] , S[5] , S[5] , S[1] ] == {{I*gc7, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[1] ] == {{(-2*I)*b0*gc8*(mdq - msq), 0}, {(3*I)*gc8, 0}, {(3*I)*gc8, 0}, {(-6*I)*gc8, 0}, {(-6*I)*gc8, 0}, {(3*I)*gc8, 0}, {(3*I)*gc8, 0}},

C[ S[5] , S[4] , -S[4] , S[1] ] == {{(2*I)*b0*gc9*(msq - muq), 0}, {(3*I)*gc9, 0}, {(3*I)*gc9, 0}, {(-6*I)*gc9, 0}, {(-6*I)*gc9, 0}, {(3*I)*gc9, 0}, {(3*I)*gc9, 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{I*gc10, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(2*I)*b0*gc11*(3*mdq + msq), 0}, {(2*I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(2*I)*gc11, 0}},

C[ S[4] , -S[4] , S[1] , S[1] ] == {{(2*I)*b0*gc12*(msq + 3*muq), 0}, {(2*I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(2*I)*gc12, 0}},

C[ S[5] , S[1] , S[1] , S[1] ] == {{I*gc13, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{I*gc14, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] ] == {{(-I)*b0*gc15*(mdq - 2*msq + muq), 0}, {(3*I)*gc15, 0}, {(3*I)*gc15, 0}, {(-6*I)*gc15, 0}, {(-6*I)*gc15, 0}, {(3*I)*gc15, 0}, {(3*I)*gc15, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] ] == {{I*b0*gc16*(mdq - muq), 0}, {0, 0}, {(3*I)*gc16, 0}, {(-3*I)*gc16, 0}, {(-3*I)*gc16, 0}, {(3*I)*gc16, 0}, {0, 0}},

C[ S[5] , S[3] , S[4] , -S[2] ] == {{(-I)*b0*gc17*(mdq - 2*msq + muq), 0}, {(3*I)*gc17, 0}, {(3*I)*gc17, 0}, {(-6*I)*gc17, 0}, {(-6*I)*gc17, 0}, {(3*I)*gc17, 0}, {(3*I)*gc17, 0}},

C[ S[3] , S[4] , S[1] , -S[2] ] == {{I*b0*gc18*(mdq - muq), 0}, {0, 0}, {(3*I)*gc18, 0}, {(-3*I)*gc18, 0}, {(-3*I)*gc18, 0}, {(3*I)*gc18, 0}, {0, 0}},

C[ S[5] , S[5] , S[2] , -S[2] ] == {{I*gc19, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] ] == {{I*b0*gc20*(2*mdq + msq + muq), 0}, {I*gc20, 0}, {(-2*I)*gc20, 0}, {I*gc20, 0}, {I*gc20, 0}, {(-2*I)*gc20, 0}, {I*gc20, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] ] == {{I*b0*gc21*(mdq + msq + 2*muq), 0}, {I*gc21, 0}, {(-2*I)*gc21, 0}, {I*gc21, 0}, {I*gc21, 0}, {(-2*I)*gc21, 0}, {I*gc21, 0}},

C[ S[5] , S[1] , S[2] , -S[2] ] == {{I*gc22, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] ] == {{I*b0*gc23*(mdq + muq), 0}, {(2*I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(2*I)*gc23, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{(-2*I)*b0*gc24*(mdq + muq), 0}, {(2*I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(2*I)*gc24, 0}},

C[ S[5] , S[5] , S[7] ] == {{I*b0*gc25*(mdq + 4*msq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(324*I)*gc25*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[5] , S[5] , S[7] ] == {{I*gc26, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[7] ] == {{I*b0*gc27*(mdq + msq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc27*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[3] , -S[3] , S[7] ] == {{I*b0*gc28*(mdq + 3*msq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(324*I)*gc28*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-162*I)*gc28*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-162*I)*gc28*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-162*I)*gc28*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-162*I)*gc28*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc28*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] , S[7] ] == {{(-I)*b0*gc29*(mdq + msq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc29*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc29*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc29*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc29*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc29*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc29*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] , S[7] ] == {{I*b0*gc30*(mdq + 2*msq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc30*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc30*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-216*I)*gc30*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-216*I)*gc30*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc30*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc30*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] ] == {{I*b0*gc31*(msq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc31*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[4] , -S[4] , S[7] ] == {{I*b0*gc32*(3*msq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(324*I)*gc32*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-162*I)*gc32*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-162*I)*gc32*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-162*I)*gc32*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-162*I)*gc32*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc32*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] , S[7] ] == {{(-I)*b0*gc33*(msq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc33*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc33*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc33*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc33*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc33*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc33*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[7] ] == {{I*gc34, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[5] , S[1] , S[7] ] == {{I*gc35, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[1] , S[7] ] == {{(-I)*b0*gc36*(mdq - msq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(162*I)*gc36*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(162*I)*gc36*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-324*I)*gc36*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-324*I)*gc36*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(162*I)*gc36*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(162*I)*gc36*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[4] , -S[4] , S[1] , S[7] ] == {{I*b0*gc37*(msq - muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(162*I)*gc37*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(162*I)*gc37*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-324*I)*gc37*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-324*I)*gc37*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(162*I)*gc37*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(162*I)*gc37*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[7] ] == {{I*b0*gc38*(mdq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc38*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[1] , S[1] , S[7] ] == {{I*gc39, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] , S[1] , S[7] ] == {{I*b0*gc40*(3*mdq + msq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc40*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc40*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc40*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc40*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc40*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc40*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[1] , S[1] , S[7] ] == {{I*b0*gc41*(msq + 3*muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc41*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc41*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc41*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc41*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc41*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc41*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[1] , S[1] , S[7] ] == {{I*gc42, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[7] ] == {{I*gc43, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] , S[7] ] == {{(-I)*b0*gc44*(mdq - 2*msq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(324*I)*gc44*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc44*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-648*I)*gc44*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-648*I)*gc44*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc44*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc44*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] , S[7] ] == {{I*b0*gc45*(mdq - muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {0, 0}, {(324*I)*gc45*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-324*I)*gc45*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-324*I)*gc45*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc45*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , S[4] , -S[2] , S[7] ] == {{(-I)*b0*gc46*(mdq - 2*msq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(324*I)*gc46*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc46*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-648*I)*gc46*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-648*I)*gc46*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc46*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc46*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[4] , S[1] , -S[2] , S[7] ] == {{I*b0*gc47*(mdq - muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {0, 0}, {(324*I)*gc47*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-324*I)*gc47*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-324*I)*gc47*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(324*I)*gc47*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , S[7] ] == {{I*b0*gc48*(mdq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc48*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[2] , -S[2] , S[7] ] == {{I*gc49, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] , S[7] ] == {{I*b0*gc50*(2*mdq + msq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc50*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-216*I)*gc50*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc50*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc50*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-216*I)*gc50*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc50*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] , S[7] ] == {{I*b0*gc51*(mdq + msq + 2*muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc51*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-216*I)*gc51*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc51*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc51*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-216*I)*gc51*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc51*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[2] , -S[2] , S[7] ] == {{I*gc52, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , S[7] ] == {{I*b0*gc53*(mdq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(216*I)*gc53*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-108*I)*gc53*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-108*I)*gc53*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-108*I)*gc53*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-108*I)*gc53*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(216*I)*gc53*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , S[7] ] == {{(-I)*b0*gc54*(mdq + muq)*(9*vh + 4*(3*gsGG)*vs)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)), 0}, {(108*I)*gc54*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc54*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc54*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc54*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(-54*I)*gc54*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {(108*I)*gc54*(3*gsGG)*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[7] , S[7] ] == {{I*gc55, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[7] , S[7] ] == {{I*gc56, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] , S[7] ] == {{I*gc57, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[7] , S[7] ] == {{I*gc58, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[7] , S[7] ] == {{I*gc59, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , S[7] , S[7] ] == {{I*gc60, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{I*gc61, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[1] , V[1] ] == {{I*gc62, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] , V[1] , V[1] ] == {{((8*I)*(3*gsGG)*qe^2)/(9*vh + 4*(3*gsGG)*vs), 0}},

C[ S[2] , -S[2] , S[7] , V[1] , V[1] ] == {{((8*I)*(3*gsGG)*qe^2)/(9*vh + 4*(3*gsGG)*vs), 0}},

C[ S[5] , -S[3] , -S[4] , S[2] , V[1] ] == {{(3*I)*gc65, 0}, {(-3*I)*gc65, 0}, {(-I)*gc65, 0}, {I*gc65, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , S[4] , -S[2] , V[1] ] == {{(3*I)*gc66, 0}, {(-3*I)*gc66, 0}, {(-I)*gc66, 0}, {I*gc66, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] , V[1] ] == {{(3*I)*gc67, 0}, {(-3*I)*gc67, 0}, {(-I)*gc67, 0}, {I*gc67, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[4] , S[1] , -S[2] , V[1] ] == {{I*gc68, 0}, {(-I)*gc68, 0}, {(-I)*gc68, 0}, {I*gc68, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] , V[1] ] == {{(-3*I)*gc69, 0}, {(3*I)*gc69, 0}, {(-I)*gc69, 0}, {I*gc69, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] , V[1] ] == {{I*gc70, 0}, {(-I)*gc70, 0}, {(-I)*gc70, 0}, {I*gc70, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*gc71, 0}, {I*gc71, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[4] , -S[4] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*gc72, 0}, {I*gc72, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] , V[1] ] == {{(-I)*gc73, 0}, {(-I)*gc73, 0}, {I*gc73, 0}, {I*gc73, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[4] , -S[4] , S[1] , V[1] ] == {{0, 0}, {(-I)*gc74, 0}, {I*gc74, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[1] , S[1] , V[1] ] == {{(-I)*gc75, 0}, {I*gc75, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] , V[1] ] == {{(-I)*gc76, 0}, {I*gc76, 0}, {(-I)*gc76, 0}, {I*gc76, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] , V[1] ] == {{(-81*I)*fpi^2*gc77*mrhoT^2*vh^2, 0}, {(81*I)*fpi^2*gc77*mrhoT^2*vh^2, 0}, {(-2*I)*contactRhoSCoeff*fv*gc77*gv*(9*vh + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs), 0}, {(2*I)*contactRhoSCoeff*fv*gc77*gv*(9*vh + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[1] ] == {{(-I)*gc78, 0}, {I*gc78, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*gc79, 0}, {I*gc79, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , V[1] ] == {{(-I)*gc80, 0}, {(-I)*gc80, 0}, {I*gc80, 0}, {I*gc80, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , S[7] , V[1] ] == {{(-81*I)*fpi^2*gc81*mrhoT^2*vh^2, 0}, {(81*I)*fpi^2*gc81*mrhoT^2*vh^2, 0}, {(-2*I)*contactRhoSCoeff*fv*gc81*gv*(9*vh + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs), 0}, {(2*I)*contactRhoSCoeff*fv*gc81*gv*(9*vh + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[7] , V[1] , V[1] ] == {{(-I)*gc82, 0}, {I*gc82, 0}},

C[ S[5] , S[5] , S[3] , -S[3] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-2*I)*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-2*I)*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc83*mrhoT*vh, 0}, {(9*I)*gc83*mrhoT*vh, 0}, {(-I)*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc83*mrhoT*vh, 0}, {(9*I)*gc83*mrhoT*vh, 0}, {(2*I)*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(2*I)*gc83*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc83*mrhoT*vh, 0}, {(9*I)*gc83*mrhoT*vh, 0}, {(-36*I)*gc83*mrhoT*vh, 0}, {(-9*I)*gc83*mrhoT*vh, 0}, {(-9*I)*gc83*mrhoT*vh, 0}, {(36*I)*gc83*mrhoT*vh, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[4] , -S[4] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(2*I)*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(2*I)*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc84*mrhoT*vh, 0}, {(9*I)*gc84*mrhoT*vh, 0}, {I*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc84*mrhoT*vh, 0}, {(9*I)*gc84*mrhoT*vh, 0}, {(-2*I)*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-2*I)*gc84*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc84*mrhoT*vh, 0}, {(9*I)*gc84*mrhoT*vh, 0}, {(-36*I)*gc84*mrhoT*vh, 0}, {(-9*I)*gc84*mrhoT*vh, 0}, {(-9*I)*gc84*mrhoT*vh, 0}, {(36*I)*gc84*mrhoT*vh, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[1] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(2*I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(2*I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc85*mrhoT*vh, 0}, {0, 0}, {(2*I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-6*I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-36*I)*gc85*mrhoT*vh, 0}, {(9*I)*gc85*mrhoT*vh, 0}, {(-I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc85*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc85*mrhoT*vh, 0}, {(36*I)*gc85*mrhoT*vh, 0}, {(-9*I)*gc85*mrhoT*vh, 0}, {0, 0}, {(-9*I)*gc85*mrhoT*vh, 0}, {(9*I)*gc85*mrhoT*vh, 0}, {(-9*I)*gc85*mrhoT*vh, 0}, {(9*I)*gc85*mrhoT*vh, 0}},

C[ S[5] , S[3] , S[4] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-4*I)*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(4*I)*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc86*mrhoT*vh, 0}, {(-36*I)*gc86*mrhoT*vh, 0}, {0, 0}, {0, 0}, {(3*I)*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {0, 0}, {(27*I)*gc86*mrhoT*vh, 0}, {(-3*I)*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc86*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc86*mrhoT*vh, 0}, {0, 0}, {(27*I)*gc86*mrhoT*vh, 0}, {(36*I)*gc86*mrhoT*vh, 0}, {(-27*I)*gc86*mrhoT*vh, 0}, {(-27*I)*gc86*mrhoT*vh, 0}, {(-9*I)*gc86*mrhoT*vh, 0}, {(9*I)*gc86*mrhoT*vh, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc87, 0}, {(-I)*gc87, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc87, 0}, {(-I)*gc87, 0}, {0, 0}, {0, 0}, {I*gc87, 0}, {I*gc87, 0}, {0, 0}, {I*gc87, 0}, {I*gc87, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(I/3)*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I/3)*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I/3)*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(I/3)*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {((4*I)/3)*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {((-4*I)/3)*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc88*mrhoT*vh, 0}, {(-12*I)*gc88*mrhoT*vh, 0}, {0, 0}, {0, 0}, {(-I)*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {0, 0}, {(9*I)*gc88*mrhoT*vh, 0}, {I*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc88*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc88*mrhoT*vh, 0}, {0, 0}, {(9*I)*gc88*mrhoT*vh, 0}, {(12*I)*gc88*mrhoT*vh, 0}, {(-9*I)*gc88*mrhoT*vh, 0}, {(-9*I)*gc88*mrhoT*vh, 0}, {(-3*I)*gc88*mrhoT*vh, 0}, {(3*I)*gc88*mrhoT*vh, 0}},

C[ S[3] , -S[3] , V[2] ] == {{0, 0}, {0, 0}, {(-I)*gc89, 0}, {I*gc89, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc90*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc90*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {0, 0}, {0, 0}, {I*gc90*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc90*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {0, 0}, {(6*I)*gc90*mrhoT*vh, 0}, {I*gc90*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc90*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {0, 0}, {0, 0}, {(-6*I)*gc90*mrhoT*vh, 0}, {0, 0}, {(-I)*gc90*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc90*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {0, 0}, {(6*I)*gc90*mrhoT*vh, 0}, {(-3*I)*gc90*mrhoT*vh, 0}, {(-6*I)*gc90*mrhoT*vh, 0}, {0, 0}, {(3*I)*gc90*mrhoT*vh, 0}, {(-3*I)*gc90*mrhoT*vh, 0}, {(3*I)*gc90*mrhoT*vh, 0}},

C[ S[3] , -S[3] , S[1] , S[1] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-2*I)*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-2*I)*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc91*mrhoT*vh, 0}, {(3*I)*gc91*mrhoT*vh, 0}, {(-I)*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc91*mrhoT*vh, 0}, {(-3*I)*gc91*mrhoT*vh, 0}, {(2*I)*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(2*I)*gc91*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc91*mrhoT*vh, 0}, {(3*I)*gc91*mrhoT*vh, 0}, {0, 0}, {(-3*I)*gc91*mrhoT*vh, 0}, {(3*I)*gc91*mrhoT*vh, 0}, {0, 0}, {(-12*I)*gc91*mrhoT*vh, 0}, {(12*I)*gc91*mrhoT*vh, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc92*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc92*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc92*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc92*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {0, 0}, {0, 0}, {(-6*I)*gc92*mrhoT*vh, 0}, {(-9*I)*gc92*mrhoT*vh, 0}, {0, 0}, {0, 0}, {I*gc92*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc92*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc92*mrhoT*vh, 0}, {(6*I)*gc92*mrhoT*vh, 0}, {(-I)*gc92*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc92*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(6*I)*gc92*mrhoT*vh, 0}, {(-9*I)*gc92*mrhoT*vh, 0}, {(-12*I)*gc92*mrhoT*vh, 0}, {(9*I)*gc92*mrhoT*vh, 0}, {(-6*I)*gc92*mrhoT*vh, 0}, {(12*I)*gc92*mrhoT*vh, 0}, {(-6*I)*gc92*mrhoT*vh, 0}, {(6*I)*gc92*mrhoT*vh, 0}},

C[ S[5] , S[4] , -S[4] , S[1] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-2*I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-2*I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc93*mrhoT*vh, 0}, {0, 0}, {(-2*I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(6*I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-36*I)*gc93*mrhoT*vh, 0}, {(9*I)*gc93*mrhoT*vh, 0}, {I*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc93*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc93*mrhoT*vh, 0}, {(36*I)*gc93*mrhoT*vh, 0}, {(-9*I)*gc93*mrhoT*vh, 0}, {0, 0}, {(-9*I)*gc93*mrhoT*vh, 0}, {(9*I)*gc93*mrhoT*vh, 0}, {(-9*I)*gc93*mrhoT*vh, 0}, {(9*I)*gc93*mrhoT*vh, 0}},

C[ S[4] , -S[4] , V[1] , V[2] ] == {{0, 0}, {(-2*I)*gc94*gv, 0}, {(-2*I)*gc94*gv, 0}, {(-I)*fv*gc94, 0}, {(2*I)*gc94*gv, 0}, {(2*I)*gc94*gv, 0}, {I*fv*gc94, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc95, 0}, {(-I)*gc95, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc95, 0}, {(-I)*gc95, 0}, {0, 0}, {0, 0}, {I*gc95, 0}, {I*gc95, 0}, {0, 0}, {I*gc95, 0}, {I*gc95, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[2] ] == {{0, 0}, {0, 0}, {(-I)*gc96, 0}, {I*gc96, 0}},

C[ S[4] , -S[4] , S[1] , S[1] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(2*I)*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(2*I)*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc97*mrhoT*vh, 0}, {(3*I)*gc97*mrhoT*vh, 0}, {I*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc97*mrhoT*vh, 0}, {(-3*I)*gc97*mrhoT*vh, 0}, {(-2*I)*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-2*I)*gc97*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc97*mrhoT*vh, 0}, {(3*I)*gc97*mrhoT*vh, 0}, {0, 0}, {(-3*I)*gc97*mrhoT*vh, 0}, {(3*I)*gc97*mrhoT*vh, 0}, {0, 0}, {(-12*I)*gc97*mrhoT*vh, 0}, {(12*I)*gc97*mrhoT*vh, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc98*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc98*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc98*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc98*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {0, 0}, {0, 0}, {(-6*I)*gc98*mrhoT*vh, 0}, {(-9*I)*gc98*mrhoT*vh, 0}, {0, 0}, {0, 0}, {(-I)*gc98*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc98*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc98*mrhoT*vh, 0}, {(6*I)*gc98*mrhoT*vh, 0}, {I*gc98*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc98*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(6*I)*gc98*mrhoT*vh, 0}, {(-9*I)*gc98*mrhoT*vh, 0}, {(-12*I)*gc98*mrhoT*vh, 0}, {(9*I)*gc98*mrhoT*vh, 0}, {(-6*I)*gc98*mrhoT*vh, 0}, {(12*I)*gc98*mrhoT*vh, 0}, {(-6*I)*gc98*mrhoT*vh, 0}, {(6*I)*gc98*mrhoT*vh, 0}},

C[ S[5] , S[1] , S[2] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc99, 0}, {(-I)*gc99, 0}, {0, 0}, {I*gc99, 0}, {0, 0}, {I*gc99, 0}, {0, 0}, {0, 0}, {(-I)*gc99, 0}, {0, 0}, {(-I)*gc99, 0}, {0, 0}, {0, 0}, {0, 0}, {(2*I)*gc99, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[4] , S[1] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-2*I)*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-2*I)*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(3*I)*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-5*I)*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc100*mrhoT*vh, 0}, {(27*I)*gc100*mrhoT*vh, 0}, {(3*I)*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-5*I)*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {I*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc100*mrhoT*vh, 0}, {(-27*I)*gc100*mrhoT*vh, 0}, {(2*I)*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(2*I)*gc100*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc100*mrhoT*vh, 0}, {(-9*I)*gc100*mrhoT*vh, 0}, {0, 0}, {(-27*I)*gc100*mrhoT*vh, 0}, {(27*I)*gc100*mrhoT*vh, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(2*I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(2*I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-3*I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(5*I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-9*I)*gc101*mrhoT*vh, 0}, {(27*I)*gc101*mrhoT*vh, 0}, {(-3*I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(5*I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc101*mrhoT*vh, 0}, {(-27*I)*gc101*mrhoT*vh, 0}, {(-2*I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(-2*I)*gc101*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs), 0}, {(9*I)*gc101*mrhoT*vh, 0}, {(-9*I)*gc101*mrhoT*vh, 0}, {0, 0}, {(-27*I)*gc101*mrhoT*vh, 0}, {(27*I)*gc101*mrhoT*vh, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[1] , V[2] ] == {{0, 0}, {(-2*I)*gc102*gv, 0}, {(-2*I)*gc102*gv, 0}, {(-I)*fv*gc102, 0}, {(2*I)*gc102*gv, 0}, {(2*I)*gc102*gv, 0}, {I*fv*gc102, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc103, 0}, {I*gc103, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc103, 0}, {I*gc103, 0}, {0, 0}, {0, 0}, {I*gc103, 0}, {I*gc103, 0}, {(-4*I)*gc103, 0}, {(-I)*gc103, 0}, {(-I)*gc103, 0}, {(4*I)*gc103, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {(-I)*gc104, 0}, {I*gc104, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc105, 0}, {(-I)*gc105, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*gc105, 0}, {(-I)*gc105, 0}, {0, 0}, {0, 0}, {I*gc105, 0}, {I*gc105, 0}, {0, 0}, {I*gc105, 0}, {I*gc105, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[7] , V[1] , V[2] ] == {{(-I)*gc106, 0}, {I*gc106, 0}},

C[ -F[2] , F[2] , S[7] ] == {{I*gc107, 0}, {I*gc107, 0}, {0, 0}, {0, 0}},

C[ -F[3] , F[3] , S[7] ] == {{I*gc108, 0}, {I*gc108, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , V[1] ] == {{I*gc109, 0}, {I*gc109, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , V[2] ] == {{(-3*I)*gc110, 0}, {(-I)*gc110, 0}, {(-I)*gc110, 0}, {(3*I)*gc110, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , V[2] ] == {{I*gc111, 0}, {(2*I)*gc111, 0}, {(2*I)*gc111, 0}, {(-I)*gc111, 0}, {(-I)*gc111, 0}, {I*gc111, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , V[2] ] == {{0, 0}, {I*gc112, 0}, {I*gc112, 0}, {0, 0}, {(-I)*gc112, 0}, {I*gc112, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[2] , V[2] ] == {{0, 0}, {I*gc113, 0}, {I*gc113, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] , V[2] ] == {{(-I)*gc114, 0}, {0, 0}, {0, 0}, {I*gc114, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] , V[2] ] == {{(-2*I)*gc115, 0}, {(-I)*gc115, 0}, {(-I)*gc115, 0}, {(2*I)*gc115, 0}, {(-I)*gc115, 0}, {I*gc115, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , V[2] ] == {{(-3*I)*gc116, 0}, {I*gc116, 0}, {I*gc116, 0}, {(3*I)*gc116, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , V[2] ] == {{I*gc117, 0}, {(-2*I)*gc117, 0}, {(-2*I)*gc117, 0}, {(-I)*gc117, 0}, {(-I)*gc117, 0}, {I*gc117, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , V[2] ] == {{0, 0}, {(-I)*gc118, 0}, {(-I)*gc118, 0}, {0, 0}, {(-I)*gc118, 0}, {I*gc118, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[2] , V[2] ] == {{0, 0}, {I*gc119, 0}, {I*gc119, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] , V[2] ] == {{(-2*I)*gc120, 0}, {I*gc120, 0}, {I*gc120, 0}, {(2*I)*gc120, 0}, {(-I)*gc120, 0}, {I*gc120, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] , V[2] ] == {{(-I)*gc121, 0}, {0, 0}, {0, 0}, {I*gc121, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc122, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , V[1] ] == {{gc123, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc124, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc125, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[1] ] == {{gc126, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc127, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc128, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[3] , S[4] ] == {{-2*gc129, 0}, {gc129, 0}, {gc129, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] ] == {{(-I)*gc130, 0}, {I*gc130, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[5] , S[4] ] == {{-gc131, 0}, {-gc131, 0}, {2*gc131, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , S[1] ] == {{gc132, 0}, {-2*gc132, 0}, {gc132, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , -S[3] , S[2] ] == {{gc133, 0}, {-2*gc133, 0}, {gc133, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] ] == {{(-I)*gc134, 0}, {I*gc134, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , S[1] ] == {{-gc135, 0}, {gc135, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , -S[3] , S[2] ] == {{gc136, 0}, {-2*gc136, 0}, {gc136, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , -S[3] , S[4] ] == {{-2*gc137, 0}, {gc137, 0}, {gc137, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] ] == {{(-I)*gc138, 0}, {I*gc138, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , -S[4] , S[2] ] == {{gc139, 0}, {-2*gc139, 0}, {gc139, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] ] == {{0, 0}, {0, 0}, {-2*fpi*(-GF)*Vus, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[4] , -S[4] ] == {{-gc141, 0}, {-gc141, 0}, {2*gc141, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] ] == {{(-I)*gc142, 0}, {I*gc142, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , S[1] ] == {{-2*gc143, 0}, {gc143, 0}, {gc143, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[2] , -S[2] ] == {{-gc144, 0}, {-gc144, 0}, {2*gc144, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] ] == {{(-I)*gc145, 0}, {I*gc145, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[1] , S[2] ] == {{-gc146, 0}, {-gc146, 0}, {2*gc146, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[1] , S[2] ] == {{0, 0}, {-gc147, 0}, {gc147, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] ] == {{0, 0}, {0, 0}, {-2*fpi*(-GF)*Vud, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[2] , -S[2] ] == {{-gc149, 0}, {-gc149, 0}, {2*gc149, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , V[1] , V[2] ] == {{-gc150, 0}, {gc150, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[1] , V[2] ] == {{-gc151, 0}, {gc151, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[2] ] == {{0, 0}, {-gc152, 0}, {gc152, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , V[2] ] == {{0, 0}, {-gc153, 0}, {gc153, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc154, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , V[1] ] == {{gc155, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc156, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc157, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , V[1] ] == {{gc158, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc159, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc160, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[3] , -S[4] ] == {{-2*gc161, 0}, {gc161, 0}, {gc161, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] ] == {{(-I)*gc162, 0}, {I*gc162, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , S[5] , -S[4] ] == {{-gc163, 0}, {-gc163, 0}, {2*gc163, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , S[1] ] == {{gc164, 0}, {-2*gc164, 0}, {gc164, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , S[3] , -S[2] ] == {{gc165, 0}, {-2*gc165, 0}, {gc165, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[3] , -S[2] ] == {{-2*gc166, 0}, {gc166, 0}, {gc166, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[3] , -S[4] ] == {{gc167, 0}, {-2*gc167, 0}, {gc167, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] ] == {{(-I)*gc168, 0}, {I*gc168, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] ] == {{(-I)*gc169, 0}, {I*gc169, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , S[1] ] == {{-gc170, 0}, {gc170, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[4] , -S[4] , -S[2] ] == {{-2*gc171, 0}, {gc171, 0}, {gc171, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[4] , -S[4] , -S[4] ] == {{-2*gc172, 0}, {gc172, 0}, {gc172, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] ] == {{0, 0}, {0, 0}, {-2*fpi*(-GF)*Vus, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] ] == {{(-I)*gc174, 0}, {I*gc174, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , S[1] ] == {{-2*gc175, 0}, {gc175, 0}, {gc175, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[2] , -S[2] ] == {{gc176, 0}, {-2*gc176, 0}, {gc176, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] ] == {{(-I)*gc177, 0}, {I*gc177, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , S[1] , -S[2] ] == {{-gc178, 0}, {-gc178, 0}, {2*gc178, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , S[1] , -S[2] ] == {{0, 0}, {-gc179, 0}, {gc179, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[2] , -S[2] , -S[2] ] == {{-2*gc180, 0}, {gc180, 0}, {gc180, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] ] == {{0, 0}, {0, 0}, {-2*fpi*(-GF)*Vud, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , V[1] , V[2] ] == {{-gc182, 0}, {gc182, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , V[2] ] == {{0, 0}, {-gc183, 0}, {gc183, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[7] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc184, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[7] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc185, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , S[7] ] == {{(-I)*gc186, 0}, {I*gc186, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , S[7] ] == {{(-I)*gc187, 0}, {I*gc187, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] , S[7] ] == {{(-I)*gc188, 0}, {I*gc188, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[7] ] == {{gc189, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , S[7] ] == {{(-I)*gc190, 0}, {I*gc190, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] , S[7] ] == {{(-I)*gc191, 0}, {I*gc191, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[7] ] == {{gc192, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , S[7] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc193, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[7] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc194, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , S[7] ] == {{(-I)*gc195, 0}, {I*gc195, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] , S[7] ] == {{(-I)*gc196, 0}, {I*gc196, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , S[7] ] == {{(-I)*gc197, 0}, {I*gc197, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[7] ] == {{gc198, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , S[7] ] == {{(-I)*gc199, 0}, {I*gc199, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] , S[7] ] == {{(-I)*gc200, 0}, {I*gc200, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , S[7] ] == {{gc201, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , V[1] , V[2] ] == {{-gc202, 0}, {gc202, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , V[2] ] == {{0, 0}, {-gc203, 0}, {gc203, 0}, {0, 0}, {0, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> (b0*(mdq + 16*msq + muq))/(9*fpi^2),
     gc2 -> 1/(12*fpi^2),
     gc3 -> -1/(3*fpi^2),
     gc4 -> 1/(6*fpi^2),
     gc5 -> 1/(12*fpi^2),
     gc6 -> -1/(3*fpi^2),
     gc7 -> -(b0*(mdq - muq))/(3*Sqrt[3]*fpi^2),
     gc8 -> 1/(12*Sqrt[3]*fpi^2),
     gc9 -> -1/(12*Sqrt[3]*fpi^2),
     gc10 -> (b0*(mdq + muq))/(3*fpi^2),
     gc11 -> 1/(12*fpi^2),
     gc12 -> 1/(12*fpi^2),
     gc13 -> -((b0*(mdq - muq))/(Sqrt[3]*fpi^2)),
     gc14 -> (b0*(mdq + muq))/fpi^2,
     gc15 -> -1/(6*Sqrt[6]*fpi^2),
     gc16 -> -1/(6*Sqrt[2]*fpi^2),
     gc17 -> -1/(6*Sqrt[6]*fpi^2),
     gc18 -> -1/(6*Sqrt[2]*fpi^2),
     gc19 -> (b0*(mdq + muq))/(3*fpi^2),
     gc20 -> 1/(6*fpi^2),
     gc21 -> 1/(6*fpi^2),
     gc22 -> -(b0*(mdq - muq))/(3*Sqrt[3]*fpi^2),
     gc23 -> 1/(3*fpi^2),
     gc24 -> -1/(3*fpi^2),
     gc25 -> -1/(81*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc26 -> (b0*(mdq + 16*msq + muq)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)))/(243*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc27 -> -1/(27*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc28 -> 1/(162*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc29 -> -2/(81*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc30 -> 1/(162*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc31 -> -1/(27*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc32 -> 1/(162*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc33 -> -2/(81*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc34 -> (b0*(mdq - muq)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)))/(27*Sqrt[3]*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc35 -> -(b0*(mdq - muq)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)))/(81*Sqrt[3]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc36 -> 1/(162*Sqrt[3]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc37 -> -1/(162*Sqrt[3]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc38 -> -1/(27*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc39 -> (b0*(mdq + muq)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)))/(81*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc40 -> 1/(162*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc41 -> 1/(162*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc42 -> -(b0*(mdq - muq)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)))/(27*Sqrt[3]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc43 -> (b0*(mdq + muq)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)))/(27*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc44 -> -1/(162*Sqrt[6]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc45 -> -1/(162*Sqrt[2]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc46 -> -1/(162*Sqrt[6]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc47 -> -1/(162*Sqrt[2]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc48 -> -1/(27*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc49 -> (b0*(mdq + muq)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)))/(81*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc50 -> 1/(162*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc51 -> 1/(162*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc52 -> -(b0*(mdq - muq)*(54*(3*gsGG)*vh - 32*(3*gsGG)^2*vs + 9*gsff*(9*vh + 16*(3*gsGG)*vs)))/(81*Sqrt[3]*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc53 -> 1/(81*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc54 -> -2/(81*fpi^2*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)*(9*vh + 4*(3*gsGG)*vs)),
     gc55 -> (-16*b0*(9*gsff - 2*(3*gsGG))*(3*gsGG)*(mdq + 4*msq + muq))/(81*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc56 -> (-16*b0*(9*gsff - 2*(3*gsGG))*(3*gsGG)*(mdq + msq))/(27*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc57 -> (-16*b0*(9*gsff - 2*(3*gsGG))*(3*gsGG)*(msq + muq))/(27*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc58 -> (16*b0*(9*gsff - 2*(3*gsGG))*(3*gsGG)*(mdq - muq))/(27*Sqrt[3]*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc59 -> (-16*b0*(9*gsff - 2*(3*gsGG))*(3*gsGG)*(mdq + muq))/(27*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc60 -> (-16*b0*(9*gsff - 2*(3*gsGG))*(3*gsGG)*(mdq + muq))/(27*vh*(3*vh + 3*gsff*vs + 2*(3*gsGG)*vs)),
     gc61 -> 2*qe^2,
     gc62 -> 2*qe^2,
     gc65 -> qe/(2*Sqrt[6]*fpi^2),
     gc66 -> -qe/(2*Sqrt[6]*fpi^2),
     gc67 -> qe/(6*fpi^2),
     gc68 -> -qe/(2*Sqrt[2]*fpi^2),
     gc69 -> qe/(6*fpi^2),
     gc70 -> qe/(2*Sqrt[2]*fpi^2),
     gc71 -> -qe,
     gc72 -> qe/(2*fpi^2),
     gc73 -> (4*qe)/(3*fpi^2),
     gc74 -> qe/(2*Sqrt[3]*fpi^2),
     gc75 -> qe/(6*fpi^2),
     gc76 -> (2*qe)/(3*fpi^2),
     gc77 -> (-4*(3*gsGG)*qe)/(81*fpi^2*mrhoT^2*vh^2*(9*vh + 4*(3*gsGG)*vs)),
     gc78 -> -qe,
     gc79 -> (2*qe)/(3*fpi^2),
     gc80 -> (4*qe)/(3*fpi^2),
     gc81 -> (-4*(3*gsGG)*qe)/(81*fpi^2*mrhoT^2*vh^2*(9*vh + 4*(3*gsGG)*vs)),
     gc82 -> (alphaEM*(5*gsFF/24))/(2*Pi*vh),
     gc83 -> -gv/(72*fpi^4*mrho*mrhoT*vh),
     gc84 -> -gv/(72*fpi^4*mrho*mrhoT*vh),
     gc85 -> gv/(72*Sqrt[3]*fpi^4*mrho*mrhoT*vh),
     gc86 -> -gv/(36*Sqrt[6]*fpi^4*mrho*mrhoT*vh),
     gc87 -> -gv/(3*fpi^4*mrho),
     gc88 -> gv/(12*Sqrt[6]*fpi^4*mrho*mrhoT*vh),
     gc89 -> (gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs))/(9*fpi^2*mrho*mrhoT*vh),
     gc90 -> -gv/(18*fpi^4*mrho*mrhoT*vh),
     gc91 -> -gv/(72*fpi^4*mrho*mrhoT*vh),
     gc92 -> -gv/(36*fpi^4*mrho*mrhoT*vh),
     gc93 -> -gv/(72*Sqrt[3]*fpi^4*mrho*mrhoT*vh),
     gc94 -> (qe*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs))/(18*fpi^2*mrho*mrhoT*vh),
     gc95 -> -gv/(3*fpi^4*mrho),
     gc96 -> (gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs))/(9*fpi^2*mrho*mrhoT*vh),
     gc97 -> -gv/(72*fpi^4*mrho*mrhoT*vh),
     gc98 -> -gv/(36*fpi^4*mrho*mrhoT*vh),
     gc99 -> -(gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs))/(9*Sqrt[3]*fpi^4*mrho*mrhoT*vh),
     gc100 -> gv/(36*Sqrt[2]*fpi^4*mrho*mrhoT*vh),
     gc101 -> -gv/(36*Sqrt[2]*fpi^4*mrho*mrhoT*vh),
     gc102 -> (qe*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs))/(9*fpi^2*mrho*mrhoT*vh),
     gc103 -> -gv/(3*fpi^4*mrho),
     gc104 -> (2*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs))/(9*fpi^2*mrho*mrhoT*vh),
     gc105 -> (-2*gv)/(3*fpi^4*mrho),
     gc106 -> (-2*fv*(3*gsGG)*qe)/(9*mrhoT*vh),
     gc107 -> -((gsff*ml)/vh),
     gc108 -> -gsxx,
     gc109 -> -qe,
     gc110 -> ((-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*Sqrt[3]*fpi^2*mrho*mrhoT*vh),
     gc111 -> (Sqrt[2]*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*fpi^2*mrho*mrhoT*vh),
     gc112 -> ((-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*fpi^2*mrho*mrhoT*vh),
     gc113 -> (4*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*Sqrt[3]*fpi^2*mrho*mrhoT*vh),
     gc114 -> (4*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*fpi^2*mrho*mrhoT*vh),
     gc115 -> -(Sqrt[2]*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*fpi^2*mrho*mrhoT*vh),
     gc116 -> ((-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*Sqrt[3]*fpi^2*mrho*mrhoT*vh),
     gc117 -> (Sqrt[2]*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*fpi^2*mrho*mrhoT*vh),
     gc118 -> ((-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*fpi^2*mrho*mrhoT*vh),
     gc119 -> (-4*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*Sqrt[3]*fpi^2*mrho*mrhoT*vh),
     gc120 -> -(Sqrt[2]*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*fpi^2*mrho*mrhoT*vh),
     gc121 -> (4*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*fpi^2*mrho*mrhoT*vh),
     gc122 -> Sqrt[2]*(-GF)*qe*Vud,
     gc123 -> -2*fpi*(-GF)*qe*Vud,
     gc124 -> -2*(-GF)*qe*Vud,
     gc125 -> -(Sqrt[3]*(-GF)*qe*Vus),
     gc126 -> -2*fpi*(-GF)*qe*Vus,
     gc127 -> -((-GF)*qe*Vus),
     gc128 -> Sqrt[2]*(-GF)*qe*Vus,
     gc129 -> -((Sqrt[2/3]*(-GF)*Vud)/fpi),
     gc130 -> -(Sqrt[3]*(-GF)*Vus),
     gc131 -> ((-GF)*Vus)/fpi,
     gc132 -> -(((-GF)*Vus)/(Sqrt[3]*fpi)),
     gc133 -> -((Sqrt[2/3]*(-GF)*Vus)/fpi),
     gc134 -> Sqrt[2]*(-GF)*Vud,
     gc135 -> -((Sqrt[2]*(-GF)*Vud)/fpi),
     gc136 -> (2*(-GF)*Vud)/(3*fpi),
     gc137 -> (2*(-GF)*Vus)/(3*fpi),
     gc138 -> Sqrt[2]*(-GF)*Vus,
     gc139 -> (2*(-GF)*Vud)/(3*fpi),
     gc141 -> (-4*(-GF)*Vus)/(3*fpi),
     gc142 -> (-GF)*Vus,
     gc143 -> -((-GF)*Vus)/(3*fpi),
     gc144 -> (-2*(-GF)*Vus)/(3*fpi),
     gc145 -> -2*(-GF)*Vud,
     gc146 -> (4*(-GF)*Vud)/(3*fpi),
     gc147 -> -((Sqrt[2]*(-GF)*Vus)/fpi),
     gc149 -> (-4*(-GF)*Vud)/(3*fpi),
     gc150 -> (4*(-GF)*gv*qe*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*fpi*mrho*mrhoT*vh),
     gc151 -> (2*(-GF)*gv*qe*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*fpi*mrho*mrhoT*vh),
     gc152 -> (2*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*fpi*mrho*mrhoT*vh),
     gc153 -> (4*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*fpi*mrho*mrhoT*vh),
     gc154 -> Sqrt[2]*(-GF)*qe*Vud,
     gc155 -> 2*fpi*(-GF)*qe*Vud,
     gc156 -> -2*(-GF)*qe*Vud,
     gc157 -> -(Sqrt[3]*(-GF)*qe*Vus),
     gc158 -> 2*fpi*(-GF)*qe*Vus,
     gc159 -> -((-GF)*qe*Vus),
     gc160 -> Sqrt[2]*(-GF)*qe*Vus,
     gc161 -> -((Sqrt[2/3]*(-GF)*Vud)/fpi),
     gc162 -> Sqrt[3]*(-GF)*Vus,
     gc163 -> ((-GF)*Vus)/fpi,
     gc164 -> -(((-GF)*Vus)/(Sqrt[3]*fpi)),
     gc165 -> -((Sqrt[2/3]*(-GF)*Vus)/fpi),
     gc166 -> (2*(-GF)*Vud)/(3*fpi),
     gc167 -> (2*(-GF)*Vus)/(3*fpi),
     gc168 -> -(Sqrt[2]*(-GF)*Vus),
     gc169 -> -(Sqrt[2]*(-GF)*Vud),
     gc170 -> -((Sqrt[2]*(-GF)*Vud)/fpi),
     gc171 -> (2*(-GF)*Vud)/(3*fpi),
     gc172 -> (4*(-GF)*Vus)/(3*fpi),
     gc174 -> -((-GF)*Vus),
     gc175 -> -((-GF)*Vus)/(3*fpi),
     gc176 -> (2*(-GF)*Vus)/(3*fpi),
     gc177 -> 2*(-GF)*Vud,
     gc178 -> (4*(-GF)*Vud)/(3*fpi),
     gc179 -> -((Sqrt[2]*(-GF)*Vus)/fpi),
     gc180 -> (4*(-GF)*Vud)/(3*fpi),
     gc182 -> (4*(-GF)*gv*qe*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*fpi*mrho*mrhoT*vh),
     gc183 -> (-4*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vud)/(9*fpi*mrho*mrhoT*vh),
     gc184 -> (-8*fpi*(-GF)*(3*gsGG)*qe*Vud)/(9*vh + 4*(3*gsGG)*vs),
     gc185 -> (-8*fpi*(-GF)*(3*gsGG)*qe*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc186 -> (-4*Sqrt[3]*(-GF)*(3*gsGG)*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc187 -> (4*Sqrt[2]*(-GF)*(3*gsGG)*Vud)/(9*vh + 4*(3*gsGG)*vs),
     gc188 -> (4*Sqrt[2]*(-GF)*(3*gsGG)*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc189 -> (-8*fpi*(-GF)*(3*gsGG)*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc190 -> (4*(-GF)*(3*gsGG)*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc191 -> (-8*(-GF)*(3*gsGG)*Vud)/(9*vh + 4*(3*gsGG)*vs),
     gc192 -> (-8*fpi*(-GF)*(3*gsGG)*Vud)/(9*vh + 4*(3*gsGG)*vs),
     gc193 -> (8*fpi*(-GF)*(3*gsGG)*qe*Vud)/(9*vh + 4*(3*gsGG)*vs),
     gc194 -> (8*fpi*(-GF)*(3*gsGG)*qe*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc195 -> (4*Sqrt[3]*(-GF)*(3*gsGG)*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc196 -> (-4*Sqrt[2]*(-GF)*(3*gsGG)*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc197 -> (-4*Sqrt[2]*(-GF)*(3*gsGG)*Vud)/(9*vh + 4*(3*gsGG)*vs),
     gc198 -> (-8*fpi*(-GF)*(3*gsGG)*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc199 -> (-4*(-GF)*(3*gsGG)*Vus)/(9*vh + 4*(3*gsGG)*vs),
     gc200 -> (8*(-GF)*(3*gsGG)*Vud)/(9*vh + 4*(3*gsGG)*vs),
     gc201 -> (-8*fpi*(-GF)*(3*gsGG)*Vud)/(9*vh + 4*(3*gsGG)*vs),
     gc202 -> (2*(-GF)*gv*qe*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*fpi*mrho*mrhoT*vh),
     gc203 -> (-2*(-GF)*gv*(9*mrho*vh + 9*mrhoT*vh + 2*(3*gsGG)*mrho*vs)*Vus)/(9*fpi*mrho*mrhoT*vh)};

