(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"EFT_subGeV_DM_P",
  Authors -> {"Adam Coogan", "Logan Morrison"},
  Date -> "7/10/2018",
  Institutions -> {"UC Santa Cruz"},
  Emails -> {"acoogan@ucsc.edu", "loanmorr@ucsc.edu"},
  Version -> 1};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["\\pi", Null, "0"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mpi0,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["\\pi", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mpi,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> ComposedChar["K", Null, "0"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk0,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["K", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk,
    Indices -> {} },

S[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\eta",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> meta,
    Indices -> {} },

S[7] == {
    SelfConjugate -> True,
    PropagatorLabel -> p,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mp,
    Indices -> {} },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> A,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> ml,
    Indices -> {} },

F[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> "\\chi",
    PropagatorArrow -> Forward,
    PropagatorType -> Straight,
    Mass -> mx,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];

mpi0[ ___ ] := mpi0;
mpi[ ___ ] := mpi;
mk0[ ___ ] := mk0;
mk[ ___ ] := mk;
meta[ ___ ] := meta;
mp[ ___ ] := mp;
ml[ ___ ] := ml;
mx[ ___ ] := mx;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[5] , S[5] , S[5] , S[7] ] == {{I*gc1, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[7] ] == {{I*gc2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[4] , -S[4] , S[7] ] == {{I*gc3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[7] , S[1] ] == {{I*gc4, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[7] , S[1] ] == {{I*gc5, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] , S[1] ] == {{I*gc6, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[7] , S[1] , S[1] ] == {{I*gc7, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[7] , S[1] , S[1] , S[1] ] == {{I*gc8, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -S[3] , -S[4] , S[7] , S[2] ] == {{I*gc9, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[4] , S[7] , -S[2] ] == {{I*gc10, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[7] , S[2] , -S[2] ] == {{I*gc11, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[7] , S[1] , S[2] , -S[2] ] == {{I*gc12, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{(2*I)*qe^2, 0}},

C[ S[2] , -S[2] , V[1] , V[1] ] == {{(2*I)*qe^2, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] , V[1] ] == {{(3*I)*gc15, 0}, {(-3*I)*gc15, 0}, {(-I)*gc15, 0}, {I*gc15, 0}},

C[ S[5] , S[3] , S[4] , -S[2] , V[1] ] == {{(3*I)*gc16, 0}, {(-3*I)*gc16, 0}, {(-I)*gc16, 0}, {I*gc16, 0}},

C[ S[5] , S[5] , S[3] , -S[3] ] == {{0, 0}, {(2*I)*gc17, 0}, {(-I)*gc17, 0}, {(-I)*gc17, 0}, {(-I)*gc17, 0}, {(-I)*gc17, 0}, {(2*I)*gc17, 0}},

C[ S[5] , S[5] , S[4] , -S[4] ] == {{0, 0}, {(2*I)*gc18, 0}, {(-I)*gc18, 0}, {(-I)*gc18, 0}, {(-I)*gc18, 0}, {(-I)*gc18, 0}, {(2*I)*gc18, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] , V[1] ] == {{(3*I)*gc19, 0}, {(-3*I)*gc19, 0}, {(-I)*gc19, 0}, {I*gc19, 0}},

C[ S[3] , S[4] , S[1] , -S[2] , V[1] ] == {{I*gc20, 0}, {(-I)*gc20, 0}, {(-I)*gc20, 0}, {I*gc20, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] , V[1] ] == {{(-3*I)*gc21, 0}, {(3*I)*gc21, 0}, {(-I)*gc21, 0}, {I*gc21, 0}},

C[ S[5] , S[3] , -S[3] , S[1] ] == {{0, 0}, {I*gc22, 0}, {I*gc22, 0}, {(-2*I)*gc22, 0}, {(-2*I)*gc22, 0}, {I*gc22, 0}, {I*gc22, 0}},

C[ S[5] , S[3] , S[4] , -S[2] ] == {{0, 0}, {I*gc23, 0}, {I*gc23, 0}, {(-2*I)*gc23, 0}, {(-2*I)*gc23, 0}, {I*gc23, 0}, {I*gc23, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{0, 0}, {(2*I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(2*I)*gc24, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] , V[1] ] == {{I*gc25, 0}, {(-I)*gc25, 0}, {(-I)*gc25, 0}, {I*gc25, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] ] == {{0, 0}, {I*gc26, 0}, {I*gc26, 0}, {(-2*I)*gc26, 0}, {(-2*I)*gc26, 0}, {I*gc26, 0}, {I*gc26, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] ] == {{0, 0}, {I*gc27, 0}, {I*gc27, 0}, {(-2*I)*gc27, 0}, {(-2*I)*gc27, 0}, {I*gc27, 0}, {I*gc27, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{0, 0}, {(2*I)*gc28, 0}, {(-I)*gc28, 0}, {(-I)*gc28, 0}, {(-I)*gc28, 0}, {(-I)*gc28, 0}, {(2*I)*gc28, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] ] == {{0, 0}, {I*gc29, 0}, {(-2*I)*gc29, 0}, {I*gc29, 0}, {I*gc29, 0}, {(-2*I)*gc29, 0}, {I*gc29, 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*gc30, 0}, {I*gc30, 0}},

C[ S[5] , S[5] , S[4] , -S[4] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*gc31, 0}, {I*gc31, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] , V[1] ] == {{(-I)*gc32, 0}, {(-I)*gc32, 0}, {I*gc32, 0}, {I*gc32, 0}},

C[ S[5] , S[4] , -S[4] , S[1] , V[1] ] == {{0, 0}, {(-I)*gc33, 0}, {I*gc33, 0}, {0, 0}},

C[ S[4] , -S[4] , S[1] , S[1] , V[1] ] == {{(-I)*gc34, 0}, {I*gc34, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] , V[1] ] == {{(-I)*gc35, 0}, {I*gc35, 0}, {(-I)*gc35, 0}, {I*gc35, 0}},

C[ S[5] , S[4] , -S[4] , S[1] ] == {{0, 0}, {I*gc36, 0}, {I*gc36, 0}, {(-2*I)*gc36, 0}, {(-2*I)*gc36, 0}, {I*gc36, 0}, {I*gc36, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{0, 0}, {(2*I)*gc37, 0}, {(-I)*gc37, 0}, {(-I)*gc37, 0}, {(-I)*gc37, 0}, {(-I)*gc37, 0}, {(2*I)*gc37, 0}},

C[ S[4] , -S[4] , S[1] , S[1] ] == {{0, 0}, {(2*I)*gc38, 0}, {(-I)*gc38, 0}, {(-I)*gc38, 0}, {(-I)*gc38, 0}, {(-I)*gc38, 0}, {(2*I)*gc38, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] ] == {{0, 0}, {I*gc39, 0}, {(-2*I)*gc39, 0}, {I*gc39, 0}, {I*gc39, 0}, {(-2*I)*gc39, 0}, {I*gc39, 0}},

C[ S[3] , S[4] , S[1] , -S[2] ] == {{0, 0}, {0, 0}, {I*gc40, 0}, {(-I)*gc40, 0}, {(-I)*gc40, 0}, {I*gc40, 0}, {0, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] ] == {{0, 0}, {0, 0}, {I*gc41, 0}, {(-I)*gc41, 0}, {(-I)*gc41, 0}, {I*gc41, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] ] == {{0, 0}, {(2*I)*gc42, 0}, {(-I)*gc42, 0}, {(-I)*gc42, 0}, {(-I)*gc42, 0}, {(-I)*gc42, 0}, {(2*I)*gc42, 0}},

C[ S[2] , -S[2] , V[1] ] == {{(-I)*gc43, 0}, {I*gc43, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*gc44, 0}, {I*gc44, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , V[1] ] == {{(-I)*gc45, 0}, {(-I)*gc45, 0}, {I*gc45, 0}, {I*gc45, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{0, 0}, {(2*I)*gc46, 0}, {(-I)*gc46, 0}, {(-I)*gc46, 0}, {(-I)*gc46, 0}, {(-I)*gc46, 0}, {(2*I)*gc46, 0}},

C[ S[7] , V[1] , V[1] ] == {{(I*alphaEM*gpFF)/(Pi*vh), 0}},

C[ -F[2] , F[2] , V[1] ] == {{I*gc48, 0}, {I*gc48, 0}},

C[ -F[2] , F[2] , S[7] ] == {{I*gc49L, 0}, {I*gc49R, 0}},

C[ -F[3] , F[3] , S[7] ] == {{I*gc50L, 0}, {I*gc50R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -(b0*(gpGG*(mdq - 8*msq + muq) + (gpdd - 8*gpss + gpuu)*vh))/(3*Sqrt[3]*fpi*vh),
     gc2 -> (b0*(gpGG*msq + gpss*vh))/(Sqrt[3]*fpi*vh),
     gc3 -> (b0*(gpGG*msq + gpss*vh))/(Sqrt[3]*fpi*vh),
     gc4 -> (b0*(gpGG*(mdq - muq) + (gpdd - gpuu)*vh))/(3*fpi*vh),
     gc5 -> (b0*(gpGG*(2*mdq + msq) + (2*gpdd + gpss)*vh))/(3*fpi*vh),
     gc6 -> -(b0*(gpGG*(msq + 2*muq) + (gpss + 2*gpuu)*vh))/(3*fpi*vh),
     gc7 -> -((b0*(gpGG*(mdq + muq) + (gpdd + gpuu)*vh))/(Sqrt[3]*fpi*vh)),
     gc8 -> (b0*(gpGG*(mdq - muq) + (gpdd - gpuu)*vh))/(fpi*vh),
     gc9 -> -(Sqrt[2]*b0*(gpGG*(mdq + msq + muq) + (gpdd + gpss + gpuu)*vh))/(3*fpi*vh),
     gc10 -> -(Sqrt[2]*b0*(gpGG*(mdq + msq + muq) + (gpdd + gpss + gpuu)*vh))/(3*fpi*vh),
     gc11 -> -((b0*(gpGG*(mdq + muq) + (gpdd + gpuu)*vh))/(Sqrt[3]*fpi*vh)),
     gc12 -> (b0*(gpGG*(mdq - muq) + (gpdd - gpuu)*vh))/(3*fpi*vh),
     gc15 -> -qe/(2*Sqrt[6]*fpi^2),
     gc16 -> qe/(2*Sqrt[6]*fpi^2),
     gc17 -> 1/(4*fpi^2),
     gc18 -> 1/(4*fpi^2),
     gc19 -> -qe/(6*fpi^2),
     gc20 -> qe/(2*Sqrt[2]*fpi^2),
     gc21 -> -qe/(6*fpi^2),
     gc22 -> 1/(4*Sqrt[3]*fpi^2),
     gc23 -> -1/(2*Sqrt[6]*fpi^2),
     gc24 -> -1/(3*fpi^2),
     gc25 -> -qe/(2*Sqrt[2]*fpi^2),
     gc26 -> -1/(2*Sqrt[6]*fpi^2),
     gc27 -> 1/(6*fpi^2),
     gc28 -> 1/(12*fpi^2),
     gc29 -> 1/(6*fpi^2),
     gc30 -> qe,
     gc31 -> -qe/(2*fpi^2),
     gc32 -> (-4*qe)/(3*fpi^2),
     gc33 -> -qe/(2*Sqrt[3]*fpi^2),
     gc34 -> -qe/(6*fpi^2),
     gc35 -> (-2*qe)/(3*fpi^2),
     gc36 -> -1/(4*Sqrt[3]*fpi^2),
     gc37 -> -1/(3*fpi^2),
     gc38 -> 1/(12*fpi^2),
     gc39 -> 1/(6*fpi^2),
     gc40 -> -1/(2*Sqrt[2]*fpi^2),
     gc41 -> -1/(2*Sqrt[2]*fpi^2),
     gc42 -> 1/(3*fpi^2),
     gc43 -> qe,
     gc44 -> (-2*qe)/(3*fpi^2),
     gc45 -> (-4*qe)/(3*fpi^2),
     gc46 -> -1/(3*fpi^2),
     gc48 -> -qe,
     gc49L -> gpll,
     gc49R -> -gpll,
     gc50L -> gpxx,
     gc50R -> -gpxx};

