(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"ChiPT_expanded_pi_only",
  Authors -> {"Adam Coogan", "Logan Morrison"},
  Date -> "2/13/2018",
  Institutions -> {"UC Santa Cruz"},
  Emails -> {"acoogan@ucsc.edu", "loanmorr@ucsc.edu"},
  Version -> 1};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["\\pi", Null, "0"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mpi0,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["\\pi", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mpi,
    Indices -> {} },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> A,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\rho",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mrho,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];

mpi0[ ___ ] := mpi0;
mpi[ ___ ] := mpi;
mrho[ ___ ] := mrho;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{I*gc1, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] ] == {{I*b0*gc2*(mdq + muq), 0}, {(2*I)*gc2, 0}, {(-I)*gc2, 0}, {(-I)*gc2, 0}, {(-I)*gc2, 0}, {(-I)*gc2, 0}, {(2*I)*gc2, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{(-2*I)*b0*gc3*(mdq + muq), 0}, {(2*I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(2*I)*gc3, 0}},

C[ S[2] , -S[2] , V[1] , V[1] ] == {{I*gc4, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , V[1] , V[1] ] == {{(((-4*I)/3)*qe^2)/fpi^2, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , V[1] , V[1] ] == {{(((-16*I)/3)*qe^2)/fpi^2, 0}},

C[ S[2] , -S[2] , V[1] ] == {{(-I)*gc7, 0}, {I*gc7, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , V[1] ] == {{(-I)*gc8, 0}, {I*gc8, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , V[1] ] == {{(-I)*gc9, 0}, {(-I)*gc9, 0}, {I*gc9, 0}, {I*gc9, 0}},

C[ S[2] , -S[2] , V[1] , V[2] ] == {{0, 0}, {(-2*I)*gc10*gv, 0}, {(-2*I)*gc10*gv, 0}, {(-I)*fv*gc10, 0}, {(2*I)*gc10*gv, 0}, {(2*I)*gc10*gv, 0}, {I*fv*gc10, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {(-I)*gc11, 0}, {I*gc11, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> (b0*(mdq + muq))/fpi^2,
     gc2 -> 1/(3*fpi^2),
     gc3 -> -1/(3*fpi^2),
     gc4 -> 2*qe^2,
     gc7 -> qe,
     gc8 -> (-2*qe)/(3*fpi^2),
     gc9 -> (4*qe)/(3*fpi^2),
     gc10 -> -(qe/(fpi^2*mrho)),
     gc11 -> (2*gv)/(fpi^2*mrho)};

